[package]
name = "fastcurve_3d"
version = "0.1.0"
authors = ["gberrante <30345675+gberrante@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
